development:
  adapter: redis
  url: redis://redistogo:cbbd5ea67b0533eb92d1994b5c542c91@pike.redistogo.com:11426/

test:
  adapter: redis

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: lifelines_production
